security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        backend_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: backend_user_provider
            logout:
                path: logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
            custom_authenticator: App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/admin/hotels, roles: ROLE_ADMIN }
        - { path: ^/admin/utilisateurs, roles: ROLE_ADMIN }
        - { path: ^/admin/suites, roles: ROLE_MANAGER }
        - { path: ^/admin/reservations, roles: ROLE_MANAGER }
        - { path: ^/mon-compte, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
