parameters:
    images_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultName: 'Hypnos'
            $defaultEmail: 'patrick.barros.85@gmail.com'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
